### PR TITLE
Macos Compatibility

### PR DESCRIPTION
**Pull request by jamesgasek**
Using aligned_alloc instead of memalign, remove pthread dependency.

### CODE REVIEW

**Comment by willem640** [comment]
This works for me on macos without this patch

**Comment by superevr** [comment]
This helped me build when I wasn't able to before on an M1 mac, macOS Ventura. Thanks

**Comment by willem640** [comment]
Ah, then it probably worked for me because I don't have an M1 and I'm on an older version

**Comment by vk496** [comment]
Hello and thank you!

Your PR have some garbage (configure~ and so on). Also, please provide a github workflow for building this for mac architecture or it could break in the future and nobody would notice it.

**Pull request closed without merging**
